//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiotTelegramBot.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiotTelegramBot.Plugins.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbstractMessageTypeProcessor.
        /// </summary>
        public static string AbstractMessageTypeProcessor {
            get {
                return ResourceManager.GetString("AbstractMessageTypeProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultMessagesProcessor {
            get {
                return ResourceManager.GetString("DefaultMessagesProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker.
        /// </summary>
        public static string DockerProcessor {
            get {
                return ResourceManager.GetString("DockerProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy.
        /// </summary>
        public static string DummyProcessor {
            get {
                return ResourceManager.GetString("DummyProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        public static string EchoProcessor {
            get {
                return ResourceManager.GetString("EchoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t process such type of message.
        /// </summary>
        public static string ErrorCantProcessMessage {
            get {
                return ResourceManager.GetString("ErrorCantProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid container.
        /// </summary>
        public static string ErrorInvalidContainer {
            get {
                return ResourceManager.GetString("ErrorInvalidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message received.
        /// </summary>
        public static string ErrorInvalidMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime error occured: .
        /// </summary>
        public static string ErrorRuntime {
            get {
                return ResourceManager.GetString("ErrorRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know you, sorry.
        /// </summary>
        public static string ErrorUserNotAuthorized {
            get {
                return ResourceManager.GetString("ErrorUserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FileProcessor {
            get {
                return ResourceManager.GetString("FileProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At your command.
        /// </summary>
        public static string InfoAtYourCommand {
            get {
                return ResourceManager.GetString("InfoAtYourCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At your service.
        /// </summary>
        public static string InfoAtYourService {
            get {
                return ResourceManager.GetString("InfoAtYourService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot status changed: .
        /// </summary>
        public static string InfoBotStatusChanged {
            get {
                return ResourceManager.GetString("InfoBotStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string InfoCommand {
            get {
                return ResourceManager.GetString("InfoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string InfoCreated {
            get {
                return ResourceManager.GetString("InfoCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string InfoDelete {
            get {
                return ResourceManager.GetString("InfoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I come to serve.
        /// </summary>
        public static string InfoIcomeToServe {
            get {
                return ResourceManager.GetString("InfoIcomeToServe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string InfoImage {
            get {
                return ResourceManager.GetString("InfoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string InfoInspect {
            get {
                return ResourceManager.GetString("InfoInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string InfoLogs {
            get {
                return ResourceManager.GetString("InfoLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InfoName {
            get {
                return ResourceManager.GetString("InfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports (public:private).
        /// </summary>
        public static string InfoPorts {
            get {
                return ResourceManager.GetString("InfoPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message: .
        /// </summary>
        public static string InfoReceivedMessage {
            get {
                return ResourceManager.GetString("InfoReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string InfoRun {
            get {
                return ResourceManager.GetString("InfoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string InfoRunning {
            get {
                return ResourceManager.GetString("InfoRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string InfoStarted {
            get {
                return ResourceManager.GetString("InfoStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string InfoState {
            get {
                return ResourceManager.GetString("InfoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string InfoStats {
            get {
                return ResourceManager.GetString("InfoStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string InfoStop {
            get {
                return ResourceManager.GetString("InfoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoped.
        /// </summary>
        public static string InfoStoped {
            get {
                return ResourceManager.GetString("InfoStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string InfoTotal {
            get {
                return ResourceManager.GetString("InfoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User audit message.
        /// </summary>
        public static string InfoUserAudit {
            get {
                return ResourceManager.GetString("InfoUserAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string InfoVersion {
            get {
                return ResourceManager.GetString("InfoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Chat user list is empty, I can&apos;t process messages from any user. Please follow setup instructions.
        /// </summary>
        public static string MessageChatUserListEmpty {
            get {
                return ResourceManager.GetString("MessageChatUserListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized user for me.
        /// </summary>
        public static string MessageNotAuth {
            get {
                return ResourceManager.GetString("MessageNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message received:.
        /// </summary>
        public static string MessageReceived {
            get {
                return ResourceManager.GetString("MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select menu.
        /// </summary>
        public static string MessageSelectMenu {
            get {
                return ResourceManager.GetString("MessageSelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string RuntimeErrorProcessor {
            get {
                return ResourceManager.GetString("RuntimeErrorProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartStop Info.
        /// </summary>
        public static string StartStopInfoProcessor {
            get {
                return ResourceManager.GetString("StartStopInfoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Audit.
        /// </summary>
        public static string UserAuditProcessor {
            get {
                return ResourceManager.GetString("UserAuditProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
