//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiotTelegramBot.Plugins {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiotTelegramBot.Plugins.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbstractMessageTypeProcessor.
        /// </summary>
        public static string AbstractMessageTypeProcessor {
            get {
                return ResourceManager.GetString("AbstractMessageTypeProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DummyProcessor.
        /// </summary>
        public static string DummyProcessor {
            get {
                return ResourceManager.GetString("DummyProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EchoProcessor.
        /// </summary>
        public static string EchoProcessor {
            get {
                return ResourceManager.GetString("EchoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t process such type of message.
        /// </summary>
        public static string ErrorCantProcessMessage {
            get {
                return ResourceManager.GetString("ErrorCantProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message received.
        /// </summary>
        public static string ErrorInvalidMessage {
            get {
                return ResourceManager.GetString("ErrorInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime error occured: .
        /// </summary>
        public static string ErrorRuntime {
            get {
                return ResourceManager.GetString("ErrorRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know you, sorry.
        /// </summary>
        public static string ErrorUserNotAuthorized {
            get {
                return ResourceManager.GetString("ErrorUserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileProcessor.
        /// </summary>
        public static string FileProcessor {
            get {
                return ResourceManager.GetString("FileProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot status changed: .
        /// </summary>
        public static string InfoBotStatusChanged {
            get {
                return ResourceManager.GetString("InfoBotStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message: .
        /// </summary>
        public static string InfoReceivedMessage {
            get {
                return ResourceManager.GetString("InfoReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User audit message.
        /// </summary>
        public static string InfoUserAudit {
            get {
                return ResourceManager.GetString("InfoUserAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Chat user list is empty, I can&apos;t process messages from any user. Please follow setup instructions.
        /// </summary>
        public static string MessageChatUserListEmpty {
            get {
                return ResourceManager.GetString("MessageChatUserListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized user for me.
        /// </summary>
        public static string MessageNotAuth {
            get {
                return ResourceManager.GetString("MessageNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message received:.
        /// </summary>
        public static string MessageReceived {
            get {
                return ResourceManager.GetString("MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select menu.
        /// </summary>
        public static string MessageSelectMenu {
            get {
                return ResourceManager.GetString("MessageSelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrphainedMessagesProcessor.
        /// </summary>
        public static string OrphainedMessagesProcessor {
            get {
                return ResourceManager.GetString("OrphainedMessagesProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuntimeErrorProcessor.
        /// </summary>
        public static string RuntimeErrorProcessor {
            get {
                return ResourceManager.GetString("RuntimeErrorProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartStopInfoProcessor.
        /// </summary>
        public static string StartStopInfoProcessor {
            get {
                return ResourceManager.GetString("StartStopInfoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAuditProcessor.
        /// </summary>
        public static string UserAuditProcessor {
            get {
                return ResourceManager.GetString("UserAuditProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}